### ISSUE TITLE
After release: add link somewhere to covid sledilnik website

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#103]

**Comment by lukarenko** [comment]
This is still to be done on covid-19.sledilnik.org

**Comment by mitjapotocin** [comment]
Sory thouth this fixes this 
![image](https://user-images.githubusercontent.com/36345162/147812081-2da0a207-da3f-4646-a96b-31767b62a56f.png)

**Comment by lukarenko** [comment]
yep, it is vice-versa

**Comment by mitjapotocin** [comment]
The main nav on sledinlink is already to crowded as it is. 
Should we squeeze another one anyway?

**Comment by SterArcher** [comment]
done through post 
![Uploading image.png…]()
