### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by miaerbus** [sledilnik/zdravniki#104]
On current master branch, doctor card button is misaligned (regarding to phone and location button) and there are bunch of console errors:
![errors](https://i.imgur.com/LzHTi9X.png)

**Comment by jalezi** [comment]
@miaerbus I fixed alignement in https://github.com/sledilnik/zdravniki/pull/102/commits/05923ab7939bdb3879502a78f0f588902d55f079 on blue branch.

I am not sure but that must be MUI warnings. At the beginning I used to have `accepts.toString()`. You can see in this [commit](https://github.com/sledilnik/zdravniki/pull/102/commits/ebf3c8cade877907701687336fed29abb33922bd). Not sure if it's important.

**Comment by miaerbus** [comment]
Not that important, it's just a bit annoying to see :)
For variable accepts, we're sometimes using strings ('y'/'n'), sometimes boolean (true/false). If we unify it and stick with one or another throughout the project, the error will probably go away.

**Comment by jalezi** [comment]
Most of the errors fixed in #110.

**Comment by stefanb** [comment]
This seems to be taken care of now.
