### ISSUE TITLE
Improved tooltip for doctor

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#105]
The new design looks great. We only need to now improve the looks of tooltip to match the new design (Sprejema, doctor type...). Also, we need to add at least a button to go to Doctor page as this is very useful for mobile, to go directly to doctor page from the map (default) view (which does not show cards anymore)

![image](https://user-images.githubusercontent.com/46861689/146384817-31f74527-76a3-4392-9774-b68a4e1d39d6.png)

**Comment by lukarenko** [comment]
@bananica I think I have already seen some preview from you somewhere, right?

**Comment by bananica** [comment]
yup, here it is:
![PixelSnap 2021-12-16 at 15 12 07](https://user-images.githubusercontent.com/6833025/146387800-52bca454-8e36-460a-99e4-eb500c83cc79.png)
