### ISSUE TITLE
Cluster marker colors are misleading

### ISSUE THREAD

**Issue by mkadunc** [sledilnik/zdravniki#108]
Cluster markers use green/yellow/red to encode the size of the cluster, which interferes with individual doctors’ markers that use green and red for ne/sprejema.

I suggest using a different color scheme for clusters, e.g.:
- all clusters are blue regardless of size; or
- clusters are colored using average of ne/sprejema for all doctors inside (green if all doctors are available, red if none of them are, yellow-orange in between)

**Comment by bananica** [comment]
+1 for this. My beta tester (wife) was also complainig about it.

**Comment by stefanb** [comment]
If ther's no other dedicated API to change that it can be tweaked using CSS:
https://stackoverflow.com/questions/49538465/changing-leaflet-markercluster-icon-color-inheriting-the-rest-of-the-default-cs

**Comment by mkadunc** [comment]
CSS sounds good for simple color change. 

More advance customization would require passing `iconCreateFunction` https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

Default implementation of that is here:
https://github.com/Leaflet/Leaflet.markercluster/blob/31360f226e1a40c03c71d68b016891beb5e63370/src/MarkerClusterGroup.js#L821

**Comment by jalezi** [comment]
@mkadunc @stefanb check https://pr-110.zdravniki.sledilnik.org/ @bananica will fix colours if necessary.

**Comment by mkadunc** [comment]
looks good to me

**Comment by bananica** [comment]
I like it + much better UX me thinks.
