### ISSUE TITLE
Opening the cluster doesn't filter doctors

### ISSUE THREAD

**Issue by MarkoJuvancic** [sledilnik/zdravniki#118]
When I click on a dot which opens the cluster, the list of doctors remains the same.

![image](https://user-images.githubusercontent.com/96068297/146759872-88298165-315b-46c0-9c6f-fc60b909f6c4.png)

**Comment by stefanb** [comment]
The list on the right always shows all the doctors from the visible part of the map.

**Comment by lukarenko** [comment]
This is intentional: we always show cards of all doctors on the map. We now have tooltip with all data and click on tooltip directs you to doctor page with all data
