### ISSUE TITLE
Empty list when no search result

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#121]
![image](https://user-images.githubusercontent.com/319826/146797279-4580f109-0e65-4654-a49c-059c5a121c24.png)

bug: Missing footer, which normally looks like:
![image](https://user-images.githubusercontent.com/319826/146797495-aaa467cd-bb4d-4553-80d3-c03d94190341.png)

Optional feature: there could be a "No results, try adjusting your filter or **_search in whole map_**" with possibly the "search in whole map" resetting the map zoom and position.

**Comment by jalezi** [comment]
@bananica and I did it on purpose, but yes we should go for optional feature @stefanb
<img width="375" alt="File 20-12-2021, 17 53 19" src="https://user-images.githubusercontent.com/44704999/146803466-345e67e2-fec1-49aa-b53d-c0a6a35e7213.png">
.

**Comment by jalezi** [comment]
Another issue at least on iPhone. Footer not fully visible.

<img width="375" alt="File 20-12-2021, 17 53 19" src="https://user-images.githubusercontent.com/44704999/146805123-8bdafc52-e2d4-412a-87a4-e2c1270f79d5.png">

**Comment by lukarenko** [comment]
This is also important as people search their doctor by name and do not find it as "General Practitioner" type is selected by default and they are searching for Dentist, Pediatrician or Gynecologist. Maybe the message on empty search should make this clear.
