### ISSUE TITLE
List, popup: Useless link on institution name

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#141]
Link on institution name to institution webpage in providers list is not active anymore since clicking anywhere takes the user to the doctor card.
![image](https://user-images.githubusercontent.com/319826/147124910-4e7185bd-4993-41b9-8b7a-ce098ec8cd11.png)
Same in map popup.

Not sure if this is intended or not.
If so remove the link from the institution name, otherwise make the link work if user clicks/taps it.

**Comment by lukarenko** [comment]
remove link, leave it on details page only - it was hidden anyway
