### ISSUE TITLE
Tooltip could explain the actual data

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#171]
Eg, it makes no sense to explain why % could be lower than 100% at a doctor having the % higher than 100%:
![image](https://user-images.githubusercontent.com/319826/147462903-64edcbd8-da4e-4518-b51f-4bf97c16ed16.png)
In such cases it should explain why some have > 100, what does it mean.

**Comment by lukarenko** [comment]
We do not know why...

**Comment by SterArcher** [comment]
This has been addressed in the FAQ https://zdravniki.sledilnik.org/sl/faq#availability
