### ISSUE TITLE
More robust on bad data

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#175]
We have a doctor without id_inst (empty) in CSV and this caused crash of complete site:
![image](https://user-images.githubusercontent.com/46861689/147636790-2e3d93e8-c7ca-4d2c-ac11-4ece28cfb850.png)

**Comment by jalezi** [comment]
Should we just skip doctor if his institution doesn't exist or create dummy institution?

**Comment by lukarenko** [comment]
Fixed
