### ISSUE TITLE
Add Error Boundary

### ISSUE THREAD

**Issue by jalezi** [sledilnik/zdravniki#177]
If app crashes user doesn't know.

Use [error boundaries](https://reactjs.org/docs/error-boundaries.html) to recover from unexpected errors.

**Comment by TadejPolajnar** [comment]
Is this issue in progress? If not I would like to help.

Are there any requirements on which components should be wrapped with error boundaries?

**Comment by jalezi** [comment]
@TadejPolajnar not in progress. I was just looking if we should use [react-error-boundary](https://www.npmjs.com/package/react-error-boundary?activeTab=dependencies). Feel free to use whatever you want.

No particular requirements.

Go ahead.

**Comment by lukarenko** [comment]
Fixed
