### ISSUE TITLE
Wide screen: all toggles with text, no space for search

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#184]
Can we improve this?
![image](https://user-images.githubusercontent.com/46861689/147811192-ba64d249-f17b-44f9-8bfd-fbba1f9fa927.png)

**Comment by jalezi** [comment]
@TadejPolajnar did we broke with b54ae6e9bc12faff5e4b84c82ec83089a9bc657b?

**Comment by TadejPolajnar** [comment]
> @TadejPolajnar did we broke with [b54ae6e](https://github.com/sledilnik/zdravniki/commit/b54ae6e9bc12faff5e4b84c82ec83089a9bc657b)?

Seems like something is wrong with aad56da826030dcd1c629650d431aee5bc238c0a will fix it

**Comment by lukarenko** [comment]
This is old problem

**Comment by TadejPolajnar** [comment]
The same issue was here before my commit but with the additional gap between the text and an icon, it is more noticeable now. (Set the width to a few pixels above 1200px).
Before:
![image](https://user-images.githubusercontent.com/40028548/147816166-68ccec7f-0b92-4d95-bbb4-798b35c5ae61.png)
Now:
![image](https://user-images.githubusercontent.com/40028548/147816707-989090dc-7787-432a-a4a6-a6cd02d4bc74.png)

Maybe we can change the breakpoint where the text of inactive buttons is hidden or/and push the search bar into a new row?

**Comment by lukarenko** [comment]
just reduce breakpoint for text on inactive buttons sooner so that it still hase space for search field

**Comment by lukarenko** [comment]
Fixed
