### ISSUE TITLE
Scroll to top on doctor list has weird behavior

### ISSUE THREAD

**Issue by TadejPolajnar** [sledilnik/zdravniki#200]
- Button is not visible on mobile or smaller screens
- On larger screens, it has a fixed position (when screen height is >1100px)

This is the last item on the list
![image](https://user-images.githubusercontent.com/40028548/147914127-45b7de3f-109e-4179-9126-638020d1a266.png)

When scrolled down, the scroll to top button is visible but moves up and down with the items
![image](https://user-images.githubusercontent.com/40028548/147914494-286de0fc-1e36-40ea-b1d1-0324d93e3bcb.png)

**Comment by mitjapotocin** [comment]
I can't even find it.

**Comment by jalezi** [comment]
> I can't even find it.

I did  :) @mitjapotocin check #201.

**Comment by jalezi** [comment]
Fixed via #201
