### ISSUE TITLE
Phone number position and maybe icon?

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#25]
Currently it looks like part of institution name, would move it away from it, maybe also add phone icon in front.
![image](https://user-images.githubusercontent.com/46861689/143840029-823458fd-b794-4a4c-a07f-418b4a3439fd.png)

**Comment by stefanb** [comment]
On doctor's card the link to website and phone are too close to each other, prone to fat-finger errors

**Comment by lukarenko** [comment]
This is now done
