### ISSUE TITLE
Tooltip for accepts/availability does not work on mobile

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#27]
I have added tooltip also on Accepts/Rejects, so now we have two tooltips.
Problem is that they only show up on desktop browser, was unable to get to tooltip on mobile.
![image](https://user-images.githubusercontent.com/46861689/143856586-178f6b91-8bff-4372-82d8-594d6d427a26.png)

**Comment by jalezi** [comment]
@lukarenko it works for me. 

<img width="375" alt="File 04-12-2021, 10 21 40" src="https://user-images.githubusercontent.com/44704999/144704466-10aafd32-5e97-475d-a087-35d6fe20a09c.png">

**Comment by stefanb** [comment]
It requires a bit long tap, but eventually it shows up.

Then it can be scrolled up over the map and menu, tooltip shown out of the list 🙂
![Screenshot_20211204-112139](https://user-images.githubusercontent.com/319826/144706045-70037e7f-2c65-4f50-9960-bdd6c0d4abb5.jpg)
![Screenshot_20211204-112111](https://user-images.githubusercontent.com/319826/144706053-aaa5898b-9df2-4afa-a6fa-17510bac6d48.jpg)

**Comment by jalezi** [comment]
@stefanb if you want to play with Tooltip try passing prop enterTouchDelay = 300. default value is 700

https://mui.com/api/tooltip/

I am not at home and probably I want br near computer all day

**Comment by lukarenko** [comment]
Yes, it works, but really needs looong press. If we can shorten the delay it would be great.

**Comment by lukarenko** [comment]
This now works OK, but the problem is that the click anywhere on the card opens doctors page, therefore tooltips on Doctor Tooltip and in list of doctors does not make much sense on Mobile.
Can we prevent touch on Accepts and Availability to open Doctors page?
Cc: @bananica

**Comment by bananica** [comment]
@lukarenko one option is to remove link from the whole card and leave it just on the title, that's probably the best option since sometimes we have links for the institution as well.
