### ISSUE TITLE
Limit map bounds

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#30]
Limit min & max latitude and longitude so that user doesn't accidentally wander too far off into the dangerous areas without doctors.

**Comment by stefanb** [comment]
Nope, users can still wander off to the other side of the planet

**Comment by jalezi** [comment]
@stefanb @lukarenko  
On branch [feat/set-map-max-bounds](https://github.com/sledilnik/zdravniki/tree/feat/set-map-max-bounds) is example how to set map max bounds. The bounds that I have set are not ok.

I guess we need different max bounds for different map sizes. 

I also temporary set min zoom to 6.
