### ISSUE TITLE
Doctor card keep loading if URL is invalid

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#44]
Eg: https://stage-zdravniki.sledilnik.org/sl/zdravnik/neveljavno-ime

should show a not found (possibly 404 to prevent page from being indexed) and offer the user a link to search page with preselected doctor type

**Comment by miaerbus** [comment]
I can add a basic 404 page like we have in sledilnik website. Page not being indexed perhaps depends on #36, is somebody already working on that issue?
