### ISSUE TITLE
Markdown bugs

### ISSUE THREAD

**Issue by miaerbus** [sledilnik/zdravniki#55]
- [ ] When a paragraph starts with `<span>..</span>`, it doesn't treat `<span>..</span>` as part of a paragraph
- [ ] Support markdown in title html attribute

**Comment by jalezi** [comment]
@miaerbus Was with `scss` ok and I missed it when converting?

**Comment by miaerbus** [comment]
Your scss was ok :) 
This is something different. It's about how `span` breaks this paragraph into two parts, and we want to display `**` in title attribute as `<strong>`.

![Example](https://i.imgur.com/9sWIjTx.png)

**Comment by lukarenko** [comment]
Temporary workaround for <span> issue was done by turning around the first statement. 
![image](https://user-images.githubusercontent.com/46861689/144503691-d1541577-08ab-4f88-a7a5-3e1e51cb2ead.png)
