### ISSUE TITLE
Linting and prettier

### ISSUE THREAD

**Issue by mihaerzen** [sledilnik/zdravniki#7]
Hi!

I went ahead and had a look at some of the pull requests. The first thing I noticed is there are different coding styles used between different authors. As this is an open-source project which will hopefully have many contributors I would suggest adding some linting to enforce a certain coding style. I believe this will increase readability and make pull request reviews easier.

Personally, I would vote to adopt eslint `airbnb-typescript` as I think it fits what I have seen in the code so far. I would also add this to the CI so it will run when pull request is created.

Let me know what you think!

Thank you for your amazing contributions so far! 👏🏼

**Comment by jalezi** [comment]
Thanks @mihaerzen. Add whatever you think is necessary.

**Comment by mihaerzen** [comment]
Quick update, I am working on this I just struggled to allocate time for it.

**Comment by mihaerzen** [comment]
PR opened.
