### ISSUE TITLE
Search text box not showing current search

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#77]
1. Visit homepage https://stage-zdravniki.sledilnik.org/sl/
2. search eg for "gojimir"
3. See one search result
4. click on icon to see doctor's card
5. click back ("nazaj na imenik") on the card 
6. see one search result
7. search text box is empty❗
8. user can't clear the search criteria to see other doctors❗

**Comment by jalezi** [comment]
I was hoping to solve this when fixing #24.

btw, I think it used to search only in visible markers. At the moment it searches in all doctors.

**Comment by jalezi** [comment]
It was resolved with #93.
