### ISSUE TITLE
Report error: add sub-page

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/zdravniki#84]
We should have sub-page with title + description for Report error. We should present podpora-zdravniki@sledilnik.org address there and present as mailto: link there.

**Comment by stefanb** [comment]
I think this would be useful as general feedback.

For accepting and fixing errors in the data of specific doctors a gform could be more useful:
- linked on doctor's detail page
- automagically prefilled all current data
- input fields for correct data
- saved to Google sheet
- moderator reviews and approves/rejects the change in a separate column in the gsheet
- data project takes the approved rows from gsheet to CSV
- data project merges the CSV with data from ZZZS, overriding invalid data

**Comment by stefanb** [comment]
Moved my above idea into separate issue:
- #85

**Comment by stefanb** [comment]
Besides providing a mailto: link the page could also link to anonymous google form or even embed it in an iframe
https://paperform.co/blog/embed-google-form/

If we start to get too much spam / useless feedback / hate messages we could require only non-anonymous users to submit a form.

**Comment by lukarenko** [comment]
This is now GForm
