### ISSUE TITLE
Mechanism for accepting structured corrections

### ISSUE THREAD

**Issue by stefanb** [sledilnik/zdravniki#85]
In addition to #84 we could make the process easier to moderate.

For accepting and fixing errors in the data of specific doctors a gform could be more useful:
- linked on doctor's detail page
- automagically prefilled all current data
- input fields for correct data
- saved to Google sheet
- moderator reviews and approves/rejects the change in a separate column in the gsheet
- data project takes the approved rows from gsheet to CSV
- data project merges the CSV with data from ZZZS, overriding invalid data

_Originally posted by @stefanb in https://github.com/sledilnik/zdravniki/issues/84#issuecomment-987235656_

**Comment by lukarenko** [comment]
Fine with me if someone implements it. Hope we do not get too much spam that way.

**Comment by stefanb** [comment]
yeah, this is why i moved it out of scope of #84

**Comment by lukarenko** [comment]
This is now done
