### ISSUE TITLE
Footer with source and copyright info missing 

### ISSUE THREAD

**Issue by bananica** [sledilnik/zdravniki#90]
![PixelSnap 2021-12-08 at 03 22 39](https://user-images.githubusercontent.com/6833025/145137146-ad53a116-ed57-448b-9ff7-56f1754498dc.png)

**Comment by bananica** [comment]
I've added this one to the bottom of the doctors list and to the single dr page. Last change date is missing atm, not sure if we can get it.

**Comment by lukarenko** [comment]
@stefanb we do not have timestamp files yet, right?

**Comment by stefanb** [comment]
nope, issue is https://github.com/sledilnik/zdravniki-data/issues/4

**Comment by stefanb** [comment]
Timestamps added in sledilnik/zdravniki-data#4:
* [doctors.csv.timestamp](https://github.com/sledilnik/zdravniki-data/blob/main/csv/doctors.csv.timestamp)
* [institutions.csv.timestamp](https://github.com/sledilnik/zdravniki-data/blob/main/csv/institutions.csv.timestamp)

General footer should display the latest of the two, but we could also start with one of them.

**Comment by stefanb** [comment]
Cc @bananica @jalezi

**Comment by lukarenko** [comment]
We should just use timestamp of doctors.csv

**Comment by stefanb** [comment]
This was done in
* #173

And related... https://github.com/sledilnik/zdravniki/search?q=timestamp+&type=commits
