### ISSUE TITLE
Fix language detection

### ISSUE THREAD

**Issue by miaerbus** [sledilnik/zdravniki#95]
When a user provides a language flag in url (e.g. https://stage-zdravniki.sledilnik.org/en/), it should always load the page in this language.

**Comment by jalezi** [comment]
@stefanb I noticed you created [language-detection](https://github.com/sledilnik/zdravniki/tree/language-detection) branch.

Does anyone working on it?

**Comment by stefanb** [comment]
Nope, someone created a branch from master where my merge was the last commit.

**Comment by jalezi** [comment]
OK. Then was probably @miaerbus.

**Comment by jalezi** [comment]
Solved with #100.
